### ISSUE TITLE
AddXP with new version of Macro fails.

### ISSUE THREAD

**Issue by bluetardis** [Jagusti/fvtt-wfrp4e-gmtoolkit#148] opened 2022-07-30 00:56 UTC
Some of my players have henchmen (pets)

The prior version of the AddXP macro (2022-06-26) allows me to add XP to targeted Players and their pets.

The current version will only let me select actual player tokens associated with a player.  (not pets etc)

I have included the referenced prior version as quick reference.....

[addxp-2022-06-26.txt](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/files/9224071/addxp-2022-06-26.txt)

**Comment by bluetardis** [comment] 2022-07-30 01:07
Its not throwing a spectator error or any issues in the console.   The only alert shown is a warning "Please target one or more PC tokens first."

**Comment by Jagusti** [comment] 2022-07-30 06:06
Hey there, so this is by design. 0.9.4 sets initial group selection to the party, which is defined in Toolkit as characters assigned to players.  The "company" group type includes player-owned characters and creatures, but not vehicles. 

To use company instead: 
* On lines 9 and 21, change `"party"` to `"company"`. 

Though, I'd expect you would then get errors if the actor isn't a character (ie, is npc or creature) as they don't have XP. YMMV.  

You can find the other group type definitions around [here](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/blob/9b1032a08a79f580467b039888c5b8426a0008f4/modules/utility.mjs#L270).

**Comment by Jagusti** [comment] 2022-07-30 06:09
> The current version will only let me _select_ actual player tokens

You can change on line 12, `"targeted"` to `"selected"` if you prefer to select rather than target tokens. I've not tested it exhaustively with non-targeted interaction, so once again YMMV.

**Comment by bluetardis** [comment] 2022-07-30 06:48
Sorry for being not super accurate in my language.  I am happy to target or select.

On line 9 and 12 I changed "party" to "company" and that worked as expected.

Can I request that you give us an option (in your menu) to toggle either way.  I am assuming that if GMs target characters then they are ok with getting an error for an NPC/creature.

**Comment by bluetardis** [comment] 2022-07-31 00:02
Made changes from `party` to `company` as suggested and this is a suitable workaround.  

Enhancement going forward is https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/issues/151

**Closed as completed** 2022-07-31 00:02 UTC
Labels: wontfix
